bugfix: render and hit test portals in the correct order when they are added in different frames
rrousselGit/flutter_portal pull request #28
Opened 2021-03-07 04:33 UTC by shrouxm

hello! i think i have a fix for #15. the first commit adds a test which demonstrates the crash from #15, and the second commit is the fix. the updated code passes all existing tests

explanation: in the original code, multiple portals which are layed out during the same frame will have their overlays added to the overlay link in reverse order, so they're need to be iterated in reverse order when rendering. but a new portal added in a subsequent frame will therefore get rendered *first* instead of last. this PR fixes this behaviour with the following logic in _OverlayLink: we maintain two sets of overlays, '_overlays' and '_newOverlays'. we only ever add to '_newOverlays', and whenever accessing '_overlays' we first add the '_newOverlays' in reverse order before emptying '_newOverlays'. this way overlays added during the same frame still get added in reverse order, but an overlay added in a later frame will come after. the assumption now is that '_overlays' is not in reverse order, so we reverse the order of iteration when accessing it. i also made the sets LinkedHashSets explicitly to make clear that the iteration in insertion order is required.

i'm pretty new to flutter so i'm not sure if there's any hidden drawbacks to this method, or i've implemented things in an awkward way. in particular, i wasn't sure how to make sure '_newOverlays' gets flushed to '_overlays' exactly once per frame and instead do it every time '_overlays' is accessed which seems like it might have a subtle edge case.

fixes #15

2021-03-14 11:35 UTC, rrousselGit commented on test/widget_test.dart
> +              child: Container(
Why is this container on the top left in the golden test if it is centered?

2021-03-14 11:35 UTC, rrousselGit commented on lib/src/portal.dart
> +    for (var i = overlayLink.overlays.length - 1; i >= 0; i--) {
What is the purpose of this change?

2021-03-14 11:37 UTC, rrousselGit commented on lib/src/portal.dart
> +    while (_newOverlays.isNotEmpty) {
Don't do that in the getter

This logic should be in a separate place

2021-03-14 11:38 UTC, rrousselGit requested changes
The `overlays` logic needs a bit of refactoring

2021-03-14 11:40 UTC, rrousselGit commented
Also, could you document this approach in the code?

> this way overlays added during the same frame still get added in reverse order, but an overlay added in a later frame will come after. the assumption now is that '_overlays' is not in reverse order, so we reverse the order of iteration when accessing it. i also made the sets LinkedHashSets explicitly to make clear that the iteration in insertion order is required.



As this approach isn't very natural. We'd need a comment to explain what is happening

2021-09-22 21:35 UTC, hamirshekhawat commented
@shrouxm  Can you please update this PR?

2021-09-22 22:09 UTC, shrouxm commented
@hamirshekhawat i stopped using this library because i ran into other issues which i was unable to resolve, so i stopped working on the PR as well, sorry! i'm happy for anyone else running into the bug to take over the PR though

2021-09-22 22:09 UTC, closed without merging